export const categories = [
    { id: 1, name: "Startup company", icon: "/apartment.svg" },
    { id: 2, name: "Corporate company", icon: "/skyscrapers.svg" },
  ];
  
export  const industry: string[] = [
    "Agriculture & Forestry",
    "Automotive",
    "Construction",
    "Consulting",
    "Consumer Goods",
    "Education",
    "Energy & Utilities",
    "Entertainment & Media",
    "Financial Services",
    "Food & Beverage",
    "Government & Public Sector",
    "Healthcare & Pharmaceuticals",
    "Hospitality & Tourism",
    "Information Technology",
    "Legal Services",
    "Logistics & Transportation",
    "Manufacturing",
    "Marketing & Advertising",
    "Non-Profit & NGOs",
    "Professional Services",
    "Retail",
    "Telecommunications",
    "Textiles & Apparel",
    "Startups",
    "Personal Businesses",
    "Other",
  ];
  
 export const employeeRanges: string[] = [
    "1-5 Employees",
    "6-10 Employees",
    "11-20 Employees",
    "21-50 Employees",
    "51-100 Employees",
    "101-200 Employees",
    "201-500 Employees",
    "501-1000 Employees",
    "1001-5000 Employees",
    "5001-10,000 Employees",
    "10,001-50,000 Employees",
    "50,001+ Employees",
  ];
  
 export const businessTypes: string[] = [
    "Sole Proprietorship",
    "Partnership",
    "Corporation",
    "Limited Liability Company (LLC)",
    "Non-Profit Organization",
    "Franchise",
    "Cooperative",
    "Freelancer/Independent Contractor",
    "Startup",
    "Small Business",
    "Medium Business",
    "Large Business",
    "E-commerce",
    "Brick and Mortar",
    "Hybrid (Online & Physical)",
    "Family Business",
    "Multinational Corporation",
    "Public Company",
    "Private Company",
  ];

 export const businessCategories = [
    "Marketing",
    "Education",
    "Product management",
    "Finance",
    "Health",
    "Resources",
    "Nonprofits",
    "More...",
  ];